<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_b2-l1-16_3-b4-l1-23_4-b1-SubMenuHeader</name>
   <tag></tag>
   <elementGuidId>aeb4ebe6-52e9-4a2c-82a2-f3871acd35e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;\30 \.myv5yclwsen&quot;] .osui-submenu__header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/aside/div/div/nav/div[2]/div/div/div/div[2]/div/div/div[2]/div/div/div[1]/div/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ec7902e6-0e1b-4797-9b73-f8269b293ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-submenu__header needsclick</value>
      <webElementGuid>55ab599b-3ac1-4d03-925c-d09e1d0d4570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l1-16_3-b4-l1-23_4-b1-SubMenuHeader</value>
      <webElementGuid>d5b8b0d5-8b57-46cd-a561-1b0034ec5394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5be86a55-937e-4275-9c6f-5a39d2daeedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8b12d0aa-ca68-42c1-9393-0b0f8f041c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>b2-l1-16_3-b4-l1-23_4-b1-Items</value>
      <webElementGuid>287985d2-937d-459a-9685-b7f9d82d2110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>0667eff3-ab56-4f0f-ba45-949b1af607bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bf25e4ac-925c-45c8-a97d-30cceef0a49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Akuisisi</value>
      <webElementGuid>e53c427c-744b-424c-b2d2-0fe7034b34bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9713536cc76b770297ce3ee51866e6fd</value>
      <webElementGuid>454aa00a-3b23-4979-90cf-1166eeb181e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = '0.myv5yclwsen']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' osui-submenu__header ')]</value>
      <webElementGuid>13bc528f-13b3-4d74-bcb7-761df4d7bedb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = '0.myv5yclwsen']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' osui-submenu__header ')]</value>
      <webElementGuid>3dfaedbe-b327-499a-8c10-e642a30690ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-l1-16_3-b4-l1-23_4-b1-SubMenuHeader' and (text() = 'Akuisisi' or . = 'Akuisisi')]</value>
      <webElementGuid>ccf1721a-7d6d-49b6-98d0-4ea86793474f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
