<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_b3-b1-b1-Input_StartDate</name>
   <tag></tag>
   <elementGuidId>7b309ec6-1502-4063-ab1e-b08a838de397</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.input-date:nth-child(1) [aria-required=&quot;true&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'date' and @id = 'b3-b1-b1-Input_StartDate']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' input-date ') and (position() = 1)]//*[@aria-required = 'true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3254924d-b7e0-43e6-98f4-adf8b5628c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>342501fa-010f-4600-abb7-41e8b4f524b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>ac3d5d88-5a58-414f-9f45-32cef96198e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>06b9b0b6-906c-4092-ba55-076707d94147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2026-07-03</value>
      <webElementGuid>7328343f-abd0-4ff9-8674-90c23c671de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b1-Input_StartDate</value>
      <webElementGuid>76c6f458-7652-47dc-9c0c-4b5a05ba5207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e8e6612860ff70567328d6cc83c0218d</value>
      <webElementGuid>b60a12e4-b735-4822-8f85-bd0edfe340b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' input-date ') and (position() = 1)]//*[@aria-required = 'true']</value>
      <webElementGuid>c8480e3d-bdf0-41aa-9d5a-bcb3fa293c47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' input-date ') and (position() = 1)]//*[@aria-required = 'true']</value>
      <webElementGuid>c98d4dad-1d57-47f2-8e03-cc03ecb4bcbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b1-b1-Input_StartDate']</value>
      <webElementGuid>3c36c4c5-66a6-4fe9-b085-0f7b63a0707d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
