<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_b3-b2-l2_0-113_0-Input_TenggatWaktuPenyeles</name>
   <tag></tag>
   <elementGuidId>17f28e5f-375c-4761-887d-833591303451</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control.OSFillParent[type=&quot;date&quot;][value=&quot;&quot;][aria-required=&quot;false&quot;][data-input=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div/div/div/div[3]/div/div/div/form/div[1]/table/tbody/tr/td[16]/div/div/div[2]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3cbed381-fc2b-409b-a7aa-f3b1ab643e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>82826583-0eb4-4e30-9055-dd9e1be98562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>229620da-6421-4ce3-b108-d27a4e396657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a2c25e34-26d4-4836-b6e1-66ed3d5a3702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>2026-07-03</value>
      <webElementGuid>f253d30c-e0f3-47e3-8a18-b530404cb210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-l2_0-113_0-Input_TenggatWaktuPenyelesaian</value>
      <webElementGuid>56477115-b455-4c2a-9f56-94cb2a52748e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4ca22b3286c2df6e1b5555b440b5b1c5</value>
      <webElementGuid>686b392b-d5fe-4b4e-8002-1d9c49699596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-control ') and contains(concat(' ', normalize-space(@class), ' '), ' OSFillParent ') and (@type = 'date') and (@value = '') and (@aria-required = 'false') and (@data-input = '')]</value>
      <webElementGuid>7f7495b8-320c-4a78-9030-9501b332e1f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-control ') and contains(concat(' ', normalize-space(@class), ' '), ' OSFillParent ') and (@type = 'date') and (@value = '') and (@aria-required = 'false') and (@data-input = '')]</value>
      <webElementGuid>886291cf-1d59-41f5-b908-8287e5b82bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b2-l2_0-113_0-Input_TenggatWaktuPenyelesaian']</value>
      <webElementGuid>4745bbad-1396-40e8-a82c-252c72d81a27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
