<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_startdate</name>
   <tag></tag>
   <elementGuidId>6d070818-1859-4522-a49b-514263522dee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/div/div[2]/div[1]/div/div/div[1]/div[2]/div/div[1]/div/div/div[2]/div/div/div[2]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-container=&quot;&quot;]:nth-child(1) > [data-block=&quot;SurveyKunjungan\.Item_DatePicker&quot;] .form-control.OSFillParent.text-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40ae01b2-c8a7-4665-82f1-62fc447a8b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-input OSFillParent</value>
      <webElementGuid>ae025f0d-8478-4f1b-8e21-815eb7692b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>356db5e8-8003-471f-ae0d-f1148c5fc648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>9abd23ce-5395-4cc1-b099-1505c4f301fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8a7dcf4f-22a9-4b64-b6b1-0cdcc60990eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>0f63f1dc-93a9-4385-90c8-c12a85ec20e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-b1-b4-Input_TextDate</value>
      <webElementGuid>62e7f0d9-13ac-4c93-8738-8bf0921b1087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ba6895da-0aa7-4873-b43d-8c01167dcd4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-50a6e491d3d5e35b12dedaec1a9f846c</value>
      <webElementGuid>5622a4f3-22bb-4693-acf7-f88c3fe570e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@data-container = '') and (position() = 1)]/*[@data-block = 'SurveyKunjungan.Item_DatePicker']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-control ') and contains(concat(' ', normalize-space(@class), ' '), ' OSFillParent ') and contains(concat(' ', normalize-space(@class), ' '), ' text-input ')]</value>
      <webElementGuid>8adf7e47-5f39-4b1d-970f-477238260240</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@data-container = '') and (position() = 1)]/*[@data-block = 'SurveyKunjungan.Item_DatePicker']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-control ') and contains(concat(' ', normalize-space(@class), ' '), ' OSFillParent ') and contains(concat(' ', normalize-space(@class), ' '), ' text-input ')]</value>
      <webElementGuid>7c8c9361-11ad-4a99-b3b4-e2c5d1b92a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'dd/mm/yyyy' and @id = 'b4-b1-b4-Input_TextDate']</value>
      <webElementGuid>902956aa-c827-4393-8f52-c1505734d9b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
