<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dokumen Golive</name>
   <tag></tag>
   <elementGuidId>369c64dc-5cf9-4ca5-9d2f-0ac69fd3df61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\/CSUL_RCU\/KelengkapanKredit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/aside/div/div/nav/div[2]/div/div/div/div[2]/div/div/div[2]/div/div/div[1]/div/div/div[2]/div/div/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bbcea609-b707-4630-a73e-f82a6c7eb0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>last-sub-menu-link OSFillParent</value>
      <webElementGuid>1a20f22d-0dee-49c8-bb32-cb9ede911ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/CSUL_RCU/KelengkapanKredit</value>
      <webElementGuid>9adbd127-50d1-4fd5-ac42-89cdbc7a4bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dokumen Golive</value>
      <webElementGuid>9b0e17c9-ee69-4324-b135-0647d997b48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e45f97bcab17235d2c575690e68f75a9</value>
      <webElementGuid>cfae2d47-6157-4722-9f9d-5c9dff357e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '/CSUL_RCU/KelengkapanKredit']</value>
      <webElementGuid>354413b6-e98a-49cd-9935-3cdbd1fa1359</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '/CSUL_RCU/KelengkapanKredit']</value>
      <webElementGuid>ad23725c-c64e-41c7-8563-7b1121eb3bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/CSUL_RCU/KelengkapanKredit' and (text() = 'Dokumen Golive' or . = 'Dokumen Golive')]</value>
      <webElementGuid>48b1da7d-6389-4ffd-8f4e-fa80e72fddd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
