<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_b3-b2-l4_0-194_0-Input_PICPengiriman</name>
   <tag></tag>
   <elementGuidId>3b47f134-ffef-4668-a7ae-9629ea44deb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.input-with-icon-input [type=&quot;text&quot;][value=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div/div/div/div[3]/div/div/div/div[3]/div[1]/table/tbody/tr/td[4]/div/div/div/div[2]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1aaf110-1e63-4d03-95a3-65fe5ec0d480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>1d1cfbdd-2f2e-4fbb-a370-9877679592c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d1df0935-cd10-45d0-9514-87d4fbc13f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7203eef4-64f0-4290-8925-80bc86c17d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e0f44562-b687-4ab1-8f2c-fd82f862e4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-l4_0-194_0-Input_PICPengiriman</value>
      <webElementGuid>f4485944-c7c0-440f-91ee-9e7901664add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2d339e531cd956f77907874e602c1d6e</value>
      <webElementGuid>1daab78f-2378-4a54-a6ed-0111ca4d5761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' input-with-icon-input ')]//*[(@type = 'text') and (@value = '')]</value>
      <webElementGuid>7b415558-7c5d-4c93-b37c-b46a3440c5fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' input-with-icon-input ')]//*[(@type = 'text') and (@value = '')]</value>
      <webElementGuid>30e0eb05-2c96-416e-a836-78fe29680279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b3-b2-l4_0-194_0-Input_PICPengiriman']</value>
      <webElementGuid>c549fb7e-0bf5-48f3-9b6e-2e06c9f7a798</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
