<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_b3-b2-b16-Input_NamaKaryawan</name>
   <tag></tag>
   <elementGuidId>7016c783-c770-4132-bebf-19dd7b28a50c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.OSInline[data-container=&quot;&quot;]:nth-child(4) [type=&quot;search&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div/div/div[2]/div[1]/div[4]/div/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54b353f2-bc66-4f2d-a8b7-ed3e51c17b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>16c82acc-3cfb-4426-814d-e2a1b7a25501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>7f23e8ab-91b3-4363-b391-9a6e6be04ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f790e380-5b15-4b82-a1f9-b4a543eef01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>bf18e0eb-5820-4285-aeb2-64aa628c5908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-b16-Input_NamaKaryawan</value>
      <webElementGuid>92334c72-6586-48ca-953e-fd49d0ce26f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fc001777ae67c43a5b7dc4f9015b1c8d</value>
      <webElementGuid>729f057b-3576-4da9-9fb2-5cdbc8f34f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' OSInline ') and (@data-container = '') and (position() = 4)]//*[@type = 'search']</value>
      <webElementGuid>9f0f77a4-a187-48a1-81c9-e1f097217b91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' OSInline ') and (@data-container = '') and (position() = 4)]//*[@type = 'search']</value>
      <webElementGuid>b1268d05-c0b3-4689-a7c8-51813331540a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'b3-b2-b16-Input_NamaKaryawan']</value>
      <webElementGuid>ae7744a9-ba07-4baf-8c68-948055ff2774</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
