<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_b3-b2-l4_0-194_0-Dropdown3</name>
   <tag></tag>
   <elementGuidId>8ef90af7-e739-4b76-b347-8a56bfd99eaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[required=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div/div/div/div[3]/div/div/div/div[3]/div[1]/table/tbody/tr/td[10]/div/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>130e49ac-6e54-4167-8504-24d49417788a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>4b258661-30d5-45d1-abe5-5a001d852dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9db21c58-63df-47df-bf50-639a99831fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-l4_0-194_0-Dropdown3</value>
      <webElementGuid>76cae5dd-3bea-4a9d-86cf-6310390ae387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select CategoryRendahSedangTinggi</value>
      <webElementGuid>be321508-ae22-4e37-a875-33f582ea6d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3ffeb2016fcabd641620f8d9ac09c4c1</value>
      <webElementGuid>12518485-ba69-455d-b0ea-077640b2035c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@required = '']</value>
      <webElementGuid>a477dac1-ccaf-4338-b76e-565e034e431a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@required = '']</value>
      <webElementGuid>489ed765-9a1c-4438-baed-ac60e1bfc9e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b2-l4_0-194_0-Dropdown3' and (text() = 'Select CategoryRendahSedangTinggi' or . = 'Select CategoryRendahSedangTinggi')]</value>
      <webElementGuid>c27d84d2-8154-4173-aa6a-2eb8138eb565</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
