<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Risk Control Unit Application</name>
   <tag></tag>
   <elementGuidId>ccdcfc07-8c2d-4b27-80cf-a67a9ec2b32b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.break-word</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div/div/div/div[3]/div/div/div[3]/div/div/div/a/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>43b070f6-35ba-414a-ab47-11624aefed63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>break-word</value>
      <webElementGuid>04730b94-a393-4709-b4b7-a2d850e7a437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Risk Control Unit Application</value>
      <webElementGuid>fbfad15c-bfb5-4615-8381-f33a6a557437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-dbb11484020f0bc50ccdfc0fb3132a2d</value>
      <webElementGuid>05cd9dae-ba79-42c5-8c7a-49663a27db15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' break-word ')]</value>
      <webElementGuid>8dfea98e-a10c-41a3-9d1e-a8e7e55c5759</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' break-word ')]</value>
      <webElementGuid>1f5f65ec-f887-4091-8d40-7f85a1181897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Risk Control Unit Application' or . = 'Risk Control Unit Application')]</value>
      <webElementGuid>a43b9b1b-d44b-4de7-b9f3-961847e2a296</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
