<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_b3-ButtonDraftRBU</name>
   <tag></tag>
   <elementGuidId>c989ab74-151c-4d57-8b3f-0f9093b50070</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.btn-peachorange</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div/div/div/div[3]/div/div[3]/div[2]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>046b2416-608d-4595-98b8-65a608bb2008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-peachorange</value>
      <webElementGuid>9277c77a-cd37-49b3-abb1-9a0bfe52f660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77eff389-68da-4f71-821e-8777f95a65a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-ButtonDraftRBU</value>
      <webElementGuid>2b0e6d1e-b414-43ed-83df-8b483345eb8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>302390d4-6d53-4127-baea-b9c7eacba8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-669ac14b586ece8ab01d9cb9d3e7ce7c</value>
      <webElementGuid>caa4397c-7098-4573-8da9-c9de8b51dfcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-peachorange ')]</value>
      <webElementGuid>f7813b52-3481-48e3-bc5f-76eda21e8b5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-peachorange ')]</value>
      <webElementGuid>18ffc9ae-5e96-4045-b7b2-c073f7a29c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b3-ButtonDraftRBU' and (text() = 'Draft' or . = 'Draft')]</value>
      <webElementGuid>9e400c86-6476-4b5f-b943-6f691d806604</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
