<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_12</name>
   <tag></tag>
   <elementGuidId>66e0fdc1-e4bc-4b3d-9f71-7dbfbb913c68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-l2-222_0-b11-b1-l2-339_2-b1-l4_0-342_3-Catatan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div[3]/div[1]/section/section/div/div/div[1]/article/div/div/div/div/div[2]/div/div[3]/div[2]/div/div/div[2]/div/div[2]/table/tbody/tr[4]/td[6]/span/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9ae617ef-d7b1-4357-a71b-af09eb4940e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-area-custom OSFillParent</value>
      <webElementGuid>3f58f56c-8c1d-4e89-ac12-2acfe3c76e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d1fda037-8a45-45a4-a520-04f999809579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>78bf774b-d5b3-4252-a1a0-486390437a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-222_0-b11-b1-l2-339_2-b1-l4_0-342_3-Catatan</value>
      <webElementGuid>a6463845-ed96-465a-b8c1-14805ba4211a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-l2-222_0-b11-b1-l2-339_2-b1-l4_0-342_3-Catatan&quot;)</value>
      <webElementGuid>d2b8dda1-76f8-4e09-934e-45431f79f83d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b3-l2-222_0-b11-b1-l2-339_2-b1-l4_0-342_3-Catatan']</value>
      <webElementGuid>7e8331f1-51f6-4808-8e99-da7a8d3414c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-l2-222_0-b11-b1-l2-339_2-b1-b2-Content']/div[2]/table/tbody/tr[4]/td[6]/span/textarea</value>
      <webElementGuid>f9c2239e-3fc6-4d35-8734-d3a4be5cea14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div[2]/div/div[2]/table/tbody/tr[4]/td[6]/span/textarea</value>
      <webElementGuid>6ea19d76-321b-4153-9b7a-4e94c1d48552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-l2-222_0-b11-b1-l2-339_2-b1-l4_0-342_3-Catatan']</value>
      <webElementGuid>ea74c190-a875-4147-be6b-264f442e038f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
