<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_38</name>
   <tag></tag>
   <elementGuidId>8de5566c-defa-4e37-b19d-fc5c6c6b5080</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-l2-222_2-b11-b2-l1-296_0-b1-l4_0-297_13-Catatan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div[3]/div[1]/section/section/div/div/div[3]/article/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div[2]/table/tbody/tr[14]/td[6]/span/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b8566d92-1e3c-41d6-ba3b-a9cff5f6b1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-area-custom OSFillParent</value>
      <webElementGuid>6d8a959f-6db4-4f70-bce7-aa12d300d10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>1fb25cb8-5f1d-4509-87ea-8c2a67d9236b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>f495e198-cab2-4d1b-8ccd-f48021752cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-222_2-b11-b2-l1-296_0-b1-l4_0-297_13-Catatan</value>
      <webElementGuid>f38cc63d-b095-4640-9179-3c1739b4a657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-l2-222_2-b11-b2-l1-296_0-b1-l4_0-297_13-Catatan&quot;)</value>
      <webElementGuid>3bccbe37-6e22-42e6-ab50-7fd67e0765cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b3-l2-222_2-b11-b2-l1-296_0-b1-l4_0-297_13-Catatan']</value>
      <webElementGuid>27c8cd5c-5af7-4e37-8651-4379b73e2912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-l2-222_2-b11-b2-l1-296_0-b1-b2-Content']/div[2]/table/tbody/tr[14]/td[6]/span/textarea</value>
      <webElementGuid>2e600ea6-748b-48d6-a3a9-d1708fd69e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td[6]/span/textarea</value>
      <webElementGuid>ee285a75-e5cf-4a54-87ba-e6c51827130a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-l2-222_2-b11-b2-l1-296_0-b1-l4_0-297_13-Catatan']</value>
      <webElementGuid>c1fd4438-b785-433d-973c-4b04a267c521</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
