<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_33</name>
   <tag></tag>
   <elementGuidId>51627202-d22b-41de-9a74-e406f194c51a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-l2-222_2-b11-b2-l1-296_0-b1-l4_0-297_8-Catatan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div[3]/div[1]/section/section/div/div/div[3]/article/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div[2]/table/tbody/tr[9]/td[6]/span/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fffaade4-40d9-4c6c-bf74-1582253a5189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-area-custom OSFillParent</value>
      <webElementGuid>756d21e1-0c88-46a9-8aff-c8547fc6e1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>96e8d1aa-37f4-4c5f-91d2-f7cb057fb5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>f8990914-c294-483b-abc1-4997dc4c90d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-222_2-b11-b2-l1-296_0-b1-l4_0-297_8-Catatan</value>
      <webElementGuid>914cf4e5-5cb3-4748-be31-79fc31c51c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-l2-222_2-b11-b2-l1-296_0-b1-l4_0-297_8-Catatan&quot;)</value>
      <webElementGuid>d3fb086b-259a-45b5-b9e4-9089bfb08b6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b3-l2-222_2-b11-b2-l1-296_0-b1-l4_0-297_8-Catatan']</value>
      <webElementGuid>7c973495-88bd-4441-8659-f35734436866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-l2-222_2-b11-b2-l1-296_0-b1-b2-Content']/div[2]/table/tbody/tr[9]/td[6]/span/textarea</value>
      <webElementGuid>43673799-10b3-4353-9930-7e795418e280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/article/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div[2]/table/tbody/tr[9]/td[6]/span/textarea</value>
      <webElementGuid>5f56c628-726b-49e9-93f1-32a5b43019fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-l2-222_2-b11-b2-l1-296_0-b1-l4_0-297_8-Catatan']</value>
      <webElementGuid>5ff3312e-4f26-41fa-981c-4cd42ca7be8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
