<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_23</name>
   <tag></tag>
   <elementGuidId>8ee28377-c318-467c-8641-139db0382816</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-l2-222_0-b11-b1-l2-339_4-b1-l4_0-344_1-Catatan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div[3]/div[1]/section/section/div/div/div[1]/article/div/div/div/div/div[2]/div/div[5]/div[2]/div/div/div[2]/div/div[2]/table/tbody/tr[2]/td[6]/span/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>034d1bd7-8d0f-4949-9fcf-50d6341b2b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-area-custom OSFillParent</value>
      <webElementGuid>6bf4764e-62fc-482f-9c1f-ccdc1e957ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>5d86761a-a684-4b16-924f-b6d59ced5d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>3436fa02-f261-4241-909e-92f4d8374e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-222_0-b11-b1-l2-339_4-b1-l4_0-344_1-Catatan</value>
      <webElementGuid>31fcf06c-d818-4afd-9668-fee9be9ccd05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-l2-222_0-b11-b1-l2-339_4-b1-l4_0-344_1-Catatan&quot;)</value>
      <webElementGuid>fb4ee247-1288-4b3c-b7ea-3ebcec8a44c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b3-l2-222_0-b11-b1-l2-339_4-b1-l4_0-344_1-Catatan']</value>
      <webElementGuid>c617f817-61c2-458c-bdd8-dae6464f20f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-l2-222_0-b11-b1-l2-339_4-b1-b2-Content']/div[2]/table/tbody/tr[2]/td[6]/span/textarea</value>
      <webElementGuid>036c5a33-ae63-43b7-a473-1a595393d96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div[2]/div/div[2]/table/tbody/tr[2]/td[6]/span/textarea</value>
      <webElementGuid>6032edde-d021-49d9-ad83-537e4c521716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-l2-222_0-b11-b1-l2-339_4-b1-l4_0-344_1-Catatan']</value>
      <webElementGuid>1e2dbea4-6f97-44bb-b209-976f3837405f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
