<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_31</name>
   <tag></tag>
   <elementGuidId>a7495566-5f7d-4cdd-b5d0-312a7361103c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-l2-222_2-b11-b2-l1-296_0-b1-l4_0-297_6-Catatan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div[3]/div[1]/section/section/div/div/div[3]/article/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div[2]/table/tbody/tr[7]/td[6]/span/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>08ec6cf9-5730-45d0-b8ae-4b4cdaaff1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-area-custom OSFillParent</value>
      <webElementGuid>977bf790-1e94-442b-9435-e1a120004d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8c2f283f-8720-4cb6-b49b-ca14bbf8eba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>06d21dd7-04b7-46f9-9ac5-f3da1aa8dbaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-222_2-b11-b2-l1-296_0-b1-l4_0-297_6-Catatan</value>
      <webElementGuid>b2cd8b2b-9ca0-4e6a-9f8c-5a299d1834d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-l2-222_2-b11-b2-l1-296_0-b1-l4_0-297_6-Catatan&quot;)</value>
      <webElementGuid>f47485f1-34f5-4a19-bb39-dc795ab9e1bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b3-l2-222_2-b11-b2-l1-296_0-b1-l4_0-297_6-Catatan']</value>
      <webElementGuid>71942a4d-ae88-4e98-9c39-14b68d6c0c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-l2-222_2-b11-b2-l1-296_0-b1-b2-Content']/div[2]/table/tbody/tr[7]/td[6]/span/textarea</value>
      <webElementGuid>fa8d3bc6-b420-42cb-9aa3-fd5e098c9fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/article/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div[2]/table/tbody/tr[7]/td[6]/span/textarea</value>
      <webElementGuid>96ec4c90-f499-4c16-9fb4-e3a9439331af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-l2-222_2-b11-b2-l1-296_0-b1-l4_0-297_6-Catatan']</value>
      <webElementGuid>db3ad351-b374-4fa3-b3ef-9b12f124517e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
