<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_8</name>
   <tag></tag>
   <elementGuidId>c8c96bee-d8dc-4d4d-8340-7771e1f97428</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-l2-222_0-b11-b1-l2-339_1-b1-l4_0-341_6-Catatan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div[3]/div[1]/section/section/div/div/div[1]/article/div/div/div/div/div[2]/div/div[2]/div[2]/div/div/div[2]/div/div[2]/table/tbody/tr[7]/td[6]/span/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>05e2265f-a7d2-4a25-97d1-b20d536febe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-area-custom OSFillParent</value>
      <webElementGuid>60e8b76a-1063-46f7-8b95-e5abe6f2167f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>fd1a7ed0-dbae-426b-8498-b1fb5fa717a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>09c7ee1e-a9b8-4873-92a9-12f0cfb0bda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-222_0-b11-b1-l2-339_1-b1-l4_0-341_6-Catatan</value>
      <webElementGuid>eef852c6-793c-47e5-bf27-965fb4d29122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-l2-222_0-b11-b1-l2-339_1-b1-l4_0-341_6-Catatan&quot;)</value>
      <webElementGuid>b722521d-3121-42ec-99dd-20fd481e68a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b3-l2-222_0-b11-b1-l2-339_1-b1-l4_0-341_6-Catatan']</value>
      <webElementGuid>b6f82198-169f-4f16-9571-b6146b3a3fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-l2-222_0-b11-b1-l2-339_1-b1-b2-Content']/div[2]/table/tbody/tr[7]/td[6]/span/textarea</value>
      <webElementGuid>255ba347-51a4-407e-80e4-a3f0877b98df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[6]/span/textarea</value>
      <webElementGuid>4a67686c-f44e-4d3e-825b-802c666c9b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-l2-222_0-b11-b1-l2-339_1-b1-l4_0-341_6-Catatan']</value>
      <webElementGuid>742fdf82-9f00-4c1f-8fda-9e24f9ac7844</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
