<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_18</name>
   <tag></tag>
   <elementGuidId>d8f738a1-d594-4049-86d2-ec804aaf665d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-l2-222_0-b11-b1-l2-339_3-b1-l4_0-343_0-Catatan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div[3]/div[1]/section/section/div/div/div[1]/article/div/div/div/div/div[2]/div/div[4]/div[2]/div/div/div[2]/div/div[2]/table/tbody/tr[1]/td[6]/span/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6a2b1ad1-b007-4d95-8b26-e2772b1bb1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-area-custom OSFillParent</value>
      <webElementGuid>92e88fe6-f441-4b49-bb8e-bb94c8082320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>123bfcd4-0dd8-4aad-a682-b68d444d2787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>4d5c1473-1415-496c-b49c-2e6669122254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-222_0-b11-b1-l2-339_3-b1-l4_0-343_0-Catatan</value>
      <webElementGuid>e16e0aec-791f-4493-938e-59962535b716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-l2-222_0-b11-b1-l2-339_3-b1-l4_0-343_0-Catatan&quot;)</value>
      <webElementGuid>09769cac-b3b6-43b5-bc09-adb3c2f1cacb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b3-l2-222_0-b11-b1-l2-339_3-b1-l4_0-343_0-Catatan']</value>
      <webElementGuid>d53e4d68-eb9c-4592-9f24-720ef7787a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-l2-222_0-b11-b1-l2-339_3-b1-b2-Content']/div[2]/table/tbody/tr/td[6]/span/textarea</value>
      <webElementGuid>10dcfdd5-f03b-4bc7-988c-17bcc6f8dafc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div[2]/div/div[2]/table/tbody/tr/td[6]/span/textarea</value>
      <webElementGuid>1d10ea31-3422-44e9-a509-d5dbc2602606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-l2-222_0-b11-b1-l2-339_3-b1-l4_0-343_0-Catatan']</value>
      <webElementGuid>0b85651e-d9a6-45f5-8a7b-5454c3c092f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
