<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_22</name>
   <tag></tag>
   <elementGuidId>15743cf2-d48a-4e36-b707-706af26ecc2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-l2-222_0-b11-b1-l2-339_4-b1-l4_0-344_0-Catatan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div[3]/div[1]/section/section/div/div/div[1]/article/div/div/div/div/div[2]/div/div[5]/div[2]/div/div/div[2]/div/div[2]/table/tbody/tr[1]/td[6]/span/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>74bfd0ff-b7ff-43fc-b3ce-26cc8280e4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-area-custom OSFillParent</value>
      <webElementGuid>bcecfad3-0ccd-4c58-9e8d-2a2ed4acf3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>5a1d464d-a92d-4776-a86f-cb63c7df3834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>e45eacea-157e-48cc-a6fd-051c59f20585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-222_0-b11-b1-l2-339_4-b1-l4_0-344_0-Catatan</value>
      <webElementGuid>0534aa0a-9c1b-480c-a96e-358105f72d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-l2-222_0-b11-b1-l2-339_4-b1-l4_0-344_0-Catatan&quot;)</value>
      <webElementGuid>89143d3e-1263-49f0-9e37-ce01a3d9a627</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b3-l2-222_0-b11-b1-l2-339_4-b1-l4_0-344_0-Catatan']</value>
      <webElementGuid>c7a6de28-fe1d-4e62-8243-40f9cb18c488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-l2-222_0-b11-b1-l2-339_4-b1-b2-Content']/div[2]/table/tbody/tr/td[6]/span/textarea</value>
      <webElementGuid>45906c53-e984-4d31-896e-dbde02a157db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div[2]/div/div[2]/table/tbody/tr/td[6]/span/textarea</value>
      <webElementGuid>b7932b11-e059-4dc0-80c7-56f777ee324a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-l2-222_0-b11-b1-l2-339_4-b1-l4_0-344_0-Catatan']</value>
      <webElementGuid>4bbf90d0-897a-4f28-ac45-64b378b1efb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
