<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_b3-l2-316_3-b10-TextArea_Catatan</name>
   <tag></tag>
   <elementGuidId>aefddfe5-c409-455d-8691-069c620bb3a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;\30 \.6hrohun12du&quot;] [data-textarea=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div/div/div/div[3]/div/div[3]/div/section/section/div/div/div[4]/article/div/div[2]/div[2]/div/div[2]/form/div/div/div[2]/div/div[2]/div[2]/div/span/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d0641aef-7d1c-445b-b20e-66cdc61a8f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>d07936d4-a67c-42e3-be39-208006a6f5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>413f1092-bd4b-47ce-a014-8e537e83f2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>63341a88-285b-4274-8c09-feb209144b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-316_3-b10-TextArea_Catatan</value>
      <webElementGuid>50faa3cd-cd26-4179-a31f-41c3f9250dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9de13f1100c376aa555d9d3cffc0a27d</value>
      <webElementGuid>bc7cd574-ab9c-4030-bab8-aca21a6e08f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = '0.6hrohun12du']//*[@data-textarea = '']</value>
      <webElementGuid>a118449c-4e80-4f28-88bf-276632d1f57d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = '0.6hrohun12du']//*[@data-textarea = '']</value>
      <webElementGuid>99348a66-1660-4118-80bd-850c4f48fd56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-l2-316_3-b10-TextArea_Catatan']</value>
      <webElementGuid>bb7b24df-bcd8-4814-b625-d026d64a63c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
