<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_b3-b2-b1-Input_StartDate2</name>
   <tag></tag>
   <elementGuidId>70f6e730-3049-44bf-a870-075c368c7726</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.input-date:nth-child(3) [aria-required=&quot;true&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' input-date ') and (position() = 3)]//*[@aria-required = 'true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48b4199c-8f45-446a-a77d-bcd05d412ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c2a4530d-43d8-4356-9fe6-99a11be8e357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>5ef3d66b-5c14-494c-9a15-12fe0d8f3b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fc6ad35d-5815-4bd8-ac72-01163506bda9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2026-06-30</value>
      <webElementGuid>753a6edd-1201-4554-a12a-1ba22d0162ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-b1-Input_StartDate2</value>
      <webElementGuid>249f28be-0eaf-46e5-a020-2f97bab50379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-173a69d9548679f32b51cf821721bf63</value>
      <webElementGuid>a7d6f9bb-5ae2-4fa7-b66f-5bd585e98eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' input-date ') and (position() = 3)]//*[@aria-required = 'true']</value>
      <webElementGuid>7290cedd-c93d-4fda-b28a-c0ccde49c040</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' input-date ') and (position() = 3)]//*[@aria-required = 'true']</value>
      <webElementGuid>72d9e948-e09d-46a5-9b5a-2bd36b1e2b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b2-b1-Input_StartDate2']</value>
      <webElementGuid>a922e3f1-9806-4740-b8b1-b688e365f6ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
