<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Staff_popup</name>
   <tag></tag>
   <elementGuidId>337a8c4c-de80-4b58-a1b9-292009a2372b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b5-Dropdown1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div/div/div[2]/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>197412af-8cc1-48d5-87d4-3a3a905bc6a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>66e31c61-5bc2-42da-a035-22422da28051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>31e88d38-fcd5-4e42-bf74-21f99791f1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b5-Dropdown1</value>
      <webElementGuid>2c891781-df4e-4e13-8a8f-d1e7068945ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select StaffIQBAL PUTRA TAWAKALGIANDI EGHY GILRANDY</value>
      <webElementGuid>2ee23042-512d-49d5-af78-b494e4f04f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b5-Dropdown1&quot;)</value>
      <webElementGuid>5a96abcd-238a-4170-bc3a-3f4054caa0ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b1-b5-Dropdown1']</value>
      <webElementGuid>2781f232-8812-45ae-9119-1d9805784dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b5-Dropdown1-container']/select</value>
      <webElementGuid>bc52dfce-a316-46e7-be02-55869689f325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign To'])[1]/following::select[1]</value>
      <webElementGuid>1790def2-8b48-4af0-8ca4-b67e869e6c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignment'])[1]/following::select[1]</value>
      <webElementGuid>cafc4718-881e-4d7a-91ca-3f91575de435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Task Type'])[1]/preceding::select[1]</value>
      <webElementGuid>5e6502a3-e044-43e4-b788-a0bfedd25fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign'])[2]/preceding::select[2]</value>
      <webElementGuid>5d68555b-d39b-443a-a07a-6b7f1fb4c345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]/div/select</value>
      <webElementGuid>a569b7d4-b818-4368-8e98-7ce2befbe9dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b1-b5-Dropdown1' and (text() = 'Select StaffIQBAL PUTRA TAWAKALGIANDI EGHY GILRANDY' or . = 'Select StaffIQBAL PUTRA TAWAKALGIANDI EGHY GILRANDY')]</value>
      <webElementGuid>26c28a3b-299c-42e6-8c43-29deb3ba39bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
