<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_b3-b2-b1-Input_StartDate3</name>
   <tag></tag>
   <elementGuidId>b7550a94-d641-4b7a-9838-c92283fe2049</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.input-date:nth-child(1) [aria-required=&quot;true&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' input-date ') and (position() = 1)]//*[@aria-required = 'true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>490489f2-7a19-40b2-ad1c-76fd727b0053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d99d4ce9-3c48-408a-8964-2b1bd4bf2c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>4dca2cf1-ef5e-489d-9682-be5cb3d2db18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1e777c72-fe5b-4147-9c50-0a84e9e68777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2026-07-01</value>
      <webElementGuid>27d971f0-0c05-4b43-ab00-e149183639d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-b1-Input_StartDate3</value>
      <webElementGuid>3838c2ea-d5ca-4597-9af9-1c4312b5f3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e8e6612860ff70567328d6cc83c0218d</value>
      <webElementGuid>bd8e529c-293c-468e-83f3-7fc3231b26f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' input-date ') and (position() = 1)]//*[@aria-required = 'true']</value>
      <webElementGuid>604db9dc-f734-4bca-8063-8d816fed84a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' input-date ') and (position() = 1)]//*[@aria-required = 'true']</value>
      <webElementGuid>0349d674-1a67-444f-9f36-09d042d33f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b2-b1-Input_StartDate3']</value>
      <webElementGuid>e8bb6e99-b159-4436-9e0a-65b92e369133</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
