<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_b3-b1-b3-b2-NamaKaryawan</name>
   <tag></tag>
   <elementGuidId>44fc5d56-9843-4eae-a4f9-96bb688c7213</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.columns-item:nth-child(1) [value=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div/div[1]/div/div[2]/div[1]/div[1]/div/div/div[1]/div/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee2dc461-9063-43e0-9e72-529cff0c6b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>489cf762-6e0f-4763-9a02-220bedacdaa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>87117add-5bbb-41f5-a9bc-5c1ae915d39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4945c844-ca04-4d25-9ce5-8f18f19b60b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>b3f7582e-a915-4998-b74f-4c8221e4f2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b3-b2-NamaKaryawan</value>
      <webElementGuid>ff4c1911-2836-4d00-98a3-7e209a3cfd17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9a36a88db0d4e8d40bd6a2165085f997</value>
      <webElementGuid>fe8a347c-61ee-449c-95f5-845b41f5f4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' columns-item ') and (position() = 1)]//*[@value = '']</value>
      <webElementGuid>e4cc0221-3ed6-4cb3-b624-1662cb428b25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' columns-item ') and (position() = 1)]//*[@value = '']</value>
      <webElementGuid>a1e4b64d-77cc-474d-9d4f-d26171a8dce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'b3-b1-b3-b2-NamaKaryawan']</value>
      <webElementGuid>ddfe6464-b9dd-4aad-8b2c-229c350c62b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
