<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pemeriksaan</name>
   <tag></tag>
   <elementGuidId>8bf904ff-227a-4560-8069-fdf176e5d7d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.popover-bottom [data-container=&quot;&quot;]:nth-child(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4d5d1a79-6f3f-4685-ba8f-d533f904dd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pemeriksaan</value>
      <webElementGuid>8079d8e7-8aaa-4c36-a19f-96198bb1e1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5351e61a5989a8d0aa42fc3126cf95fd</value>
      <webElementGuid>d26d3e10-30a4-4fcc-b30a-bd7bdc7c3bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' popover-bottom ')]//*[(@data-container = '') and (position() = 2)]</value>
      <webElementGuid>7693af10-1d3f-40ca-8a72-ee27cce20290</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' popover-bottom ')]//*[(@data-container = '') and (position() = 2)]</value>
      <webElementGuid>a2e38d9c-8aeb-4c5c-97ef-e33d80695f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pemeriksaan' or . = 'Pemeriksaan')]</value>
      <webElementGuid>6f44a637-6f2c-40b1-ad85-fa46825749ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
