<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Persetujuan</name>
   <tag></tag>
   <elementGuidId>93f4adbf-b165-4a35-b0b2-32f906d271fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.font-size-s</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-size-s ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b971aac6-3f93-4163-9159-f8a6d238260f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-size-s</value>
      <webElementGuid>ec27eb92-37c3-41e8-afde-505b55863352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Persetujuan</value>
      <webElementGuid>cafc993f-6578-4ecd-ba92-7884590b7640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-568c4b43800c21b0406ce04f8aa6685f</value>
      <webElementGuid>072ec197-1da8-4220-b85c-da1c507595a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-size-s ')]</value>
      <webElementGuid>5dcceb9c-12e4-4316-a01f-998db9cc0ed4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-size-s ')]</value>
      <webElementGuid>33c40de7-f762-494a-9956-0990f8041726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Persetujuan' or . = 'Persetujuan')]</value>
      <webElementGuid>0be54177-573a-4249-a863-7c2cb215fc19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
