<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_b3-b9-TextArea_Catatan</name>
   <tag></tag>
   <elementGuidId>a6e85113-3710-4a95-b11b-72b5b9352fe0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-textarea=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div/div/div/div[3]/div/div[5]/div/div/div[2]/form/div/div/div[1]/div/div[2]/div[2]/div/span/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>350560b6-30b3-4746-818a-5f6b1ea5dfaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>f8af664a-bbf7-4456-ba7e-ee6553cd5b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3065f058-c1b2-4cd8-be46-ad6a0f1c3725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>e328698a-e1f6-4bc5-8836-cdc7b5b9ffb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b9-TextArea_Catatan</value>
      <webElementGuid>53ad217d-96af-42e6-8c02-b8cd42a0c412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0983327a1988361bf91d51ac63252fb7</value>
      <webElementGuid>de3c7b3f-8fb2-4a0d-9af1-e88a04cae6cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-textarea = '']</value>
      <webElementGuid>67b399ee-0366-49af-b760-17c7d5822761</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-textarea = '']</value>
      <webElementGuid>44cf658c-7a0a-42df-a6a3-bb663a05322c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-b9-TextArea_Catatan']</value>
      <webElementGuid>1bf5727c-8cf3-4af4-a55b-be60746492f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
