<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_b3-b2-l3-187_0-l3-188_0-b5-l5_0-189_0-Input</name>
   <tag></tag>
   <elementGuidId>73c54a7d-5272-4240-bff5-198e0ad5dece</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[value=&quot;&quot;][type=&quot;date&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div/div/div/div[3]/div/div/div/form/div[1]/section/section/div/div/div[1]/article/div/div/div/div/div/div/table/tbody/tr/td[10]/div/div/div[2]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f29381f5-19e4-41d2-8ab6-bab718647c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>245435b7-fe2e-45e9-9a64-5dcd70fb392c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>66d41d6a-466d-4ca2-b867-208572af4768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6a701da8-960a-40c9-a67c-7fa3c6444793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>2026-07-01</value>
      <webElementGuid>9c58f64c-5edf-4e2e-b00c-e600dc1b0af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-l3-187_0-l3-188_0-b5-l5_0-189_0-Input_TenggatWaktu</value>
      <webElementGuid>36fe6bff-525e-4c48-98f3-19ebd96befc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0487c88a-99c5-41a1-934c-d5d5db9bf5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5189974dc0ac261e52e8164b11c2c17f</value>
      <webElementGuid>b261bbcd-e55b-4819-91a8-f589c4ccb848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@value = '') and (@type = 'date')]</value>
      <webElementGuid>5869fdc1-a0eb-4089-a493-e2e93bec304f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@value = '') and (@type = 'date')]</value>
      <webElementGuid>a3a5db94-08f0-4084-a73d-750bb464fb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b2-l3-187_0-l3-188_0-b5-l5_0-189_0-Input_TenggatWaktu']</value>
      <webElementGuid>a505ccc2-4239-4495-b66a-e4c0a6a7df7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
