<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_b2-l1-17_10-b3-SubMenuHeader</name>
   <tag></tag>
   <elementGuidId>807f7d35-996c-42a7-b5aa-dce28f957b45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;\30 \.nyl1h41n88&quot;] > .osui-submenu__header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/aside/div/div/nav/div[2]/div/div/div/div[4]/div/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1304810f-4336-4456-ac3b-dc3174228f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-submenu__header needsclick</value>
      <webElementGuid>6305ebb9-0c76-49c4-84fa-708b97d57a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l1-17_10-b3-SubMenuHeader</value>
      <webElementGuid>77864ea5-0474-4a20-ad8b-b4cc15b78562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>df3d4c7d-e311-47b5-ae3d-42bb34c44036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>aaf6d146-6216-4d48-9a12-f3c75c2a0fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>b2-l1-17_10-b3-Items</value>
      <webElementGuid>0dc8e1c0-eb7e-4daf-8e38-b352200a62bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>4acd2be0-53f2-42a3-a843-6e08b7b2919c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>06793eb4-4e73-4a78-88ac-6d8262fcada1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tindak Lanjut</value>
      <webElementGuid>e502661d-6b47-4dd8-a7ad-dc41da901af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d8d7634b8e239791785ec48c694289ff</value>
      <webElementGuid>673fcc4b-2d00-480d-9b47-700ecbc65ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = '0.nyl1h41n88']/*[@class and contains(concat(' ', normalize-space(@class), ' '), ' osui-submenu__header ')]</value>
      <webElementGuid>fed99515-4375-4c19-87df-3f11f4f3b90c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = '0.nyl1h41n88']/*[@class and contains(concat(' ', normalize-space(@class), ' '), ' osui-submenu__header ')]</value>
      <webElementGuid>cf97b989-dd5b-45f9-8956-cbe710908608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-l1-17_10-b3-SubMenuHeader' and (text() = 'Tindak Lanjut' or . = 'Tindak Lanjut')]</value>
      <webElementGuid>e1c7abfc-6437-44fd-8e0e-918f2d1cafc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
