<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_b3-b1-b1-Input_StartDate4</name>
   <tag></tag>
   <elementGuidId>614e846e-9329-426e-9984-f0f8f69db5e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.input-date:nth-child(3) [aria-required=&quot;true&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' input-date ') and (position() = 3)]//*[@aria-required = 'true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c41f6530-94d7-4ae8-84b9-7e2b9b02e8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>18255e75-f235-4cfc-b613-1daeb9e5e507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>f77dc076-4bc7-4778-83f6-3602f9b38a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e072763f-5608-4119-83c5-3b6cbe93a3cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2026-07-03</value>
      <webElementGuid>fdf255a0-3687-4dde-805c-58417262709a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b1-Input_StartDate4</value>
      <webElementGuid>124a508c-fabc-45c4-9807-35ed03d58631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-173a69d9548679f32b51cf821721bf63</value>
      <webElementGuid>4d63b26c-944e-41f8-8411-8578c50a561c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' input-date ') and (position() = 3)]//*[@aria-required = 'true']</value>
      <webElementGuid>4e25541e-60ad-4137-a633-a9d6f22be205</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' input-date ') and (position() = 3)]//*[@aria-required = 'true']</value>
      <webElementGuid>73b6a3b2-2963-4232-b25c-d3eb9fd023ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b1-b1-Input_StartDate4']</value>
      <webElementGuid>620ff637-5357-4790-b0d8-1be62a656230</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
